name: gamebrige
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.1.2
  pin_code_fields: ^7.4.0
  flutter_dotenv: ^5.0.2
  mailer: ^5.3.0
  fluttertoast: ^8.1.2
  loading_animation_widget: ^1.2.0+4
  flutter_keyboard_visibility: ^5.4.0
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  firebase_auth: ^4.2.5
  awesome_notifications: ^0.7.4+1
  permission_handler: ^10.2.0
  flutter_background_service: ^2.4.6
  google_sign_in: ^5.4.4
  change_app_package_name: ^1.1.0
  flutter_signin_button: ^2.0.0
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

