// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9HTu0z_9UhV8FrnQXOtcZFH9e0THNdI',
    appId: '1:747520515560:web:cb29ce1d382f68d008185d',
    messagingSenderId: '747520515560',
    projectId: 'gamebrige',
    authDomain: 'gamebrige.firebaseapp.com',
    storageBucket: 'gamebrige.appspot.com',
    measurementId: 'G-2YNM1TG1KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5bCOKkkGrluy9rtC00SUSyZPXvwnoSM',
    appId: '1:747520515560:android:ee8ab895731a5bcb08185d',
    messagingSenderId: '747520515560',
    projectId: 'gamebrige',
    storageBucket: 'gamebrige.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAx2dW2e3w8MYyrkJfAzfWaK15uvl2Tg',
    appId: '1:747520515560:ios:55dd54a60c98ddbe08185d',
    messagingSenderId: '747520515560',
    projectId: 'gamebrige',
    storageBucket: 'gamebrige.appspot.com',
    androidClientId: '747520515560-a01i70qgr3d9j3hpbi2249lnki35e4br.apps.googleusercontent.com',
    iosClientId: '747520515560-5pp66cnovp61hqgnl0nq6fe4v79278aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamebrige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpAx2dW2e3w8MYyrkJfAzfWaK15uvl2Tg',
    appId: '1:747520515560:ios:55dd54a60c98ddbe08185d',
    messagingSenderId: '747520515560',
    projectId: 'gamebrige',
    storageBucket: 'gamebrige.appspot.com',
    androidClientId: '747520515560-a01i70qgr3d9j3hpbi2249lnki35e4br.apps.googleusercontent.com',
    iosClientId: '747520515560-5pp66cnovp61hqgnl0nq6fe4v79278aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamebrige',
  );
}
