// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmv5TSxUSpyp8jpMErxKawn1EEc9aljdM',
    appId: '1:29930325525:web:33403bd2dac0f045c9301c',
    messagingSenderId: '29930325525',
    projectId: 'com-uzlas-gamebrige',
    authDomain: 'com-uzlas-gamebrige.firebaseapp.com',
    storageBucket: 'com-uzlas-gamebrige.appspot.com',
    measurementId: 'G-P6GPQ9EL99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJX9Gh_blBL-wzOcIrm-DQvbJMJCTR5r4',
    appId: '1:29930325525:android:26cab4f2bc90bd92c9301c',
    messagingSenderId: '29930325525',
    projectId: 'com-uzlas-gamebrige',
    storageBucket: 'com-uzlas-gamebrige.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9gzbbd_dFNpH-nfMlbCKUDvoQBfheOw',
    appId: '1:29930325525:ios:150838dd3f103015c9301c',
    messagingSenderId: '29930325525',
    projectId: 'com-uzlas-gamebrige',
    storageBucket: 'com-uzlas-gamebrige.appspot.com',
    androidClientId: '29930325525-md5r8q50ut0drnv4hcth2n8fghe35knr.apps.googleusercontent.com',
    iosClientId: '29930325525-junf7v97u63ko8bcs3k99l6jlb2rdsde.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamebrige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU9gzbbd_dFNpH-nfMlbCKUDvoQBfheOw',
    appId: '1:29930325525:ios:150838dd3f103015c9301c',
    messagingSenderId: '29930325525',
    projectId: 'com-uzlas-gamebrige',
    storageBucket: 'com-uzlas-gamebrige.appspot.com',
    androidClientId: '29930325525-md5r8q50ut0drnv4hcth2n8fghe35knr.apps.googleusercontent.com',
    iosClientId: '29930325525-junf7v97u63ko8bcs3k99l6jlb2rdsde.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamebrige',
  );
}
